/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\code\\vuepress-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-42b6e060",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-42b6e060").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-7f4653d3",
    path: "/font-end/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f4653d3").then(next)
    },
  },
  {
    path: "/font-end/index.html",
    redirect: "/font-end/"
  },
  {
    name: "v-1dbc5038",
    path: "/font-end/four.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1dbc5038").then(next)
    },
  },
  {
    name: "v-0d51464c",
    path: "/font-end/three.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0d51464c").then(next)
    },
  },
  {
    name: "v-60b03309",
    path: "/study/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60b03309").then(next)
    },
  },
  {
    path: "/study/index.html",
    redirect: "/study/"
  },
  {
    name: "v-9dd92b04",
    path: "/study/two.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9dd92b04").then(next)
    },
  },
  {
    name: "v-502fd83e",
    path: "/study/one.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-502fd83e").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]