/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Hello VuePress",
  "description": "Just playing around",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/hero.png",
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "actionLink": "/zh/guide/",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-42b6e060",
      "path": "/"
    },
    {
      "title": "前端",
      "frontmatter": {},
      "regularPath": "/font-end/",
      "relativePath": "font-end/README.md",
      "key": "v-7f4653d3",
      "path": "/font-end/"
    },
    {
      "title": "four",
      "frontmatter": {},
      "regularPath": "/font-end/four.html",
      "relativePath": "font-end/four.md",
      "key": "v-1dbc5038",
      "path": "/font-end/four.html"
    },
    {
      "title": "three",
      "frontmatter": {},
      "regularPath": "/font-end/three.html",
      "relativePath": "font-end/three.md",
      "key": "v-0d51464c",
      "path": "/font-end/three.html"
    },
    {
      "title": "How to build a VuePress",
      "frontmatter": {},
      "regularPath": "/study/",
      "relativePath": "study/README.md",
      "key": "v-60b03309",
      "path": "/study/",
      "headers": [
        {
          "level": 2,
          "title": "first",
          "slug": "first"
        },
        {
          "level": 2,
          "title": "second",
          "slug": "second"
        },
        {
          "level": 2,
          "title": "third",
          "slug": "third"
        }
      ]
    },
    {
      "title": "two",
      "frontmatter": {},
      "regularPath": "/study/two.html",
      "relativePath": "study/two.md",
      "key": "v-9dd92b04",
      "path": "/study/two.html"
    },
    {
      "title": "one",
      "frontmatter": {},
      "regularPath": "/study/one.html",
      "relativePath": "study/one.md",
      "key": "v-502fd83e",
      "path": "/study/one.html"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "学习",
        "link": "/study/"
      },
      {
        "text": "前端之路",
        "link": "/font-end/"
      },
      {
        "text": "更多",
        "ariaLabel": "More Menu",
        "items": [
          {
            "text": "todolist",
            "link": "/More/todolist"
          }
        ]
      },
      {
        "text": "GitHub",
        "link": "https://github.com/zoopen",
        "target": "_blank"
      }
    ],
    "sidebar": {
      "/study/": [
        "",
        "one",
        "two"
      ],
      "/font-end/": [
        "three",
        "four"
      ]
    }
  }
}